name: Workflow for testing things in GHA
on:
  workflow_dispatch: {}

env:
  REGISTRY: "ghcr.io"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image: ${{ steps.image-output.outputs.image }}
    steps:

    - name: test outputs
      id: image-output
      run: |
        tag=$(echo ${{ github.ref }} | cut -d'/' -f3)
        image="${REGISTRY}/${{ github.repository }}:$tag"
        echo "image=${image}" >> "$GITHUB_OUTPUT"
        

  test-output:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      image: ${{ needs.build.outputs.image }}
    steps:
    - run: echo $image
